language: python

cache: pip

jobs:
  include:
    - stage: lint
      python: "3.8"
      install: pip install mypy black flake8
      script:
        - black --check .
        - mypy src
        - flake8 src tests
    - stage: package
      python: "3.8"
      install: pip install setl
      script: setl dist
  allow_failures:
    - python: "nightly"

# python:
#   - "3.8"
#   - "3.7"
#   - "nightly"

# install:
#   - pip install setl
#   - setl install

# script: pytest tests
